services:
  database-test:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  web-app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - database-test
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always

  redis:
    image: redis:latest
    hostname: redis
    restart: always

  celery_worker:
    build:
      context: .
    hostname: celery_worker
    entrypoint: celery
    command: -A config.celery.app worker -l info
    volumes:
      - ./src:/src
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - redis
    restart: always
  
  celery_beat:
    build:
      context: .
    hostname: celery_beat
    entrypoint: celery
    command: -A config.celery.app beat -l info
    volumes:
      - ./src:/src
    env_file:
      - .env
    links:
      - redis
    depends_on:
      - redis
    restart: always

volumes:
  database:
